export const items =  [
  {
    id: 1,
    category: 'cloths',
    title: "women top",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTpA0hNPZ9Xysji9xM4LQrXQYWvdmRjp4kRaHupDE0wq_rFYbH7Ojc2KY-UObanRBkAqPiBoF36XfXlNKQG9q2gM-JMcaO7o9G4aJGg14JmW0qgokbWANG7mv0',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: 'Leriya Fashion Shirt for Women Women Shirt Long Shirt for Women',
    price: '399',
  },
  {
    id: 5,
    category: 'beauty-products',
    title: "beauty",
    imgSrc: 'https://orchidlifesciences.com/wp-content/uploads/2024/06/01-14-01-1024x704.jpg',
    amazonLink: 'https://amzn.to/3EzeQaC',
    description: 'Get the premium quality beauty product here ',
    price: '499',
  },
  {
    id: 7,
    category: 'jewellery',
    title: "jewellery",
    imgSrc: 'https://2.imimg.com/data2/CG/RE/MY-3025447/diamond-necklace-500x500.jpg',
    amazonLink: 'https://amzn.to/3ZeNRdY',
    description: 'Look prittier with elegance ',
    price: '299',
  },
  {
    id: 2,
    category: 'cloths',
    title: "women top",
    imgSrc: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS8oBBC7JK6-_cyMIhSPDptJUlOT0Bl32zqNDwv0chBZwGvSigRgNNS0avmaJPL5WspVHOFZHl1NP5SdZdQ601F5XpHTnNcGJ5rAIDOSGLHNRJUsBgO6nVq',
    amazonLink: 'https://amzn.to/44MiYi6',
    description: 'Leriya Fashion Western Dress | Rayon Solid Button Front Shirt Dress for Women',
    price: '499',
  },
  {
    id: 6,
    category: 'jewellery',
    title: "jewellery",
    imgSrc: 'https://i.pinimg.com/736x/0b/a6/95/0ba6952ce8dbb1b15b462849ef33abb3.jpg',
    amazonLink: 'https://amzn.to/3RabsdH',
    description: 'Look prittier with elegance ',
    price: '199',
  },
  {
    id: 3,
    category: 'beauty-products',
    title: "beauty",
    imgSrc: 'https://plus.unsplash.com/premium_photo-1673628167571-532a6c5f5d16?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    amazonLink: 'https://amzn.to/3r6XJtv',
    description: 'Get the premium quality beauty product here ',
    price: '699',
  },
  {
    id: 4,
    category: 'beauty-products',
    title: "beauty ",
    imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTvc1gkOPk_CnDDLygOchwMIMLUCsMfPLOyg&s',
    amazonLink: 'https://amzn.to/44JsK4r',
    description: 'Get the premium quality beauty product here  ',
    price: '299',
  },
  {
    id: 9,
    category: 'jewellery',
    title: "jewellery",
    imgSrc: 'https://www.orra.co.in/media/catalog/product/cache/f863675abff2fd3fa792fa24743dba0a/o/s/osn23050.jpg',
    amazonLink: 'https://amzn.to/3Pdsh4F',
    description: 'Look prittier with elegance ',

    price: '499',
  },
  {
    id: 11,
    category: 'cloths',
    title: "women top",
    imgSrc: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQCcM98COdgl0-f2PDeTMDxn0mvyXi4FomZ-JDXFXEdWw922-ZwLN6ITkCWffgtVF53K-JXFb0lTfOiKs3K060iAaNeHqJpL4Ygy0HFVoL0spE_OUj05xELRQ',
    amazonLink: 'https://amzn.to/3r9rvhm',
    description: 'Style Quotient Women Peach Self Design Lace Regular Smart Casual Top ',
    price: '699',
  },
  {
    id: 12,
    category: 'beauty-products',
    title: "beauty",
    imgSrc: 'https://m.media-amazon.com/images/I/512jT7Yc2DL._AC_.jpg',
    amazonLink: 'https://amzn.to/3r9rvhm',
    description: 'Get the premium quality beauty product here ',
    price: '899',
  },
  {
    id: 13,
    category: 'cloths',
    title: "women top",
    imgSrc: 'https://images.meesho.com/images/products/384426181/vl8w6_1200.jpg',
    amazonLink: 'https://amzn.to/3r9rvhm',
    description: ' Casual wear Full SleeveV-Neck Top for Girls ',
    price: '899',
  },
  {
    id: 14,
    category: 'jewellery',
    title: "jewellery",
    imgSrc: 'https://png.pngtree.com/thumb_back/fw800/background/20241101/pngtree-indian-kundon-jewellery-image_16489015.jpg',
    amazonLink: 'https://amzn.to/3r9rvhm',
    description: 'Look prittier with elegance  ',
    price: '599',
  },


]